// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/mdt-variants/Cockpit.tsx": () => import("../components/mockups/mdt-variants/Cockpit.tsx"),
  "./components/mockups/mdt-variants/Conversational.tsx": () => import("../components/mockups/mdt-variants/Conversational.tsx"),
  "./components/mockups/mdt-variants/DepartureBoard.tsx": () => import("../components/mockups/mdt-variants/DepartureBoard.tsx"),
  "./components/mockups/mdt-variants/EcoNavigator.tsx": () => import("../components/mockups/mdt-variants/EcoNavigator.tsx")
};
